const types = {
  SET_SINGER: 'SET_SINGER',
  SET_PLAYING_STATE: 'SET_PLAYING_STATE',
  SET_FULL_SCREEN: 'SET_FULL_SCREEN',
  SET_PLAYLIST: 'SET_PLAYLIST',
  SET_SEQUENCE_LIST: 'SET_SEQUENCE_LIST',
  SET_PLAY_MODE: 'SET_PLAY_MODE',
  SET_CURRENT_INDEX: 'SET_CURRENT_INDEX'
}

export default types
